project:
  type: website
  output-dir: .
website:
  title: "Molecular Nodes"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.md
        text: Home
      - installation.md
      - getting-started.md
      - examples.md
      - documentation.md
    tools:
      - icon: github
        href: https://github.com/BradyAJohnston/MolecularNodes
      - icon: twitter
        href: https://twitter.com/bradyajohnston
  page-footer:
    left: "This site is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#F8F9FA"
  
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-depth: 2



